version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix(dependabot): "

  - package-ecosystem: "uv"
    directory: "/xtest"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
    commit-message:
      prefix: "fix(dependabot): "
      prefix-development: "chore(dependabot): "

  - package-ecosystem: "uv"
    directory: "/otdf-local"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
    commit-message:
      prefix: "fix(dependabot): "
      prefix-development: "chore(dependabot): "

  - package-ecosystem: "uv"
    directory: "/otdf-sdk-mgr"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
    commit-message:
      prefix: "fix(dependabot): "
      prefix-development: "chore(dependabot): "
