version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      github-actions-major:
        patterns:
          - "*"
        update-types:
          - "major"
    commit-message:
      prefix: "chore(ci): "

  - package-ecosystem: "uv"
    directory: "/xtest"
    cooldown:
      default-days: 14
    schedule:
      interval: "weekly"
    groups:
      uv-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      uv-major:
        patterns:
          - "*"
        update-types:
          - "major"
    versioning-strategy: "increase"
    commit-message:
      prefix: "fix(dependabot): "
      prefix-development: "chore(dependabot): "

  - package-ecosystem: "uv"
    directory: "/otdf-local"
    cooldown:
      default-days: 14
    schedule:
      interval: "weekly"
    groups:
      uv-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      uv-major:
        patterns:
          - "*"
        update-types:
          - "major"
    versioning-strategy: "increase"
    commit-message:
      prefix: "fix(dependabot): "
      prefix-development: "chore(dependabot): "

  - package-ecosystem: "uv"
    directory: "/otdf-sdk-mgr"
    cooldown:
      default-days: 14
    schedule:
      interval: "weekly"
    groups:
      uv-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      uv-major:
        patterns:
          - "*"
        update-types:
          - "major"
    versioning-strategy: "increase"
    commit-message:
      prefix: "fix(dependabot): "
      prefix-development: "chore(dependabot): "
