[project]
name = "opentdf-tests"
version = "2.0.0"
description = "Test suite for OpenTDF"
requires-python = ">=3.13"
dependencies = [
    "annotated-types",
    "certifi",
    "cffi",
    "charset-normalizer",
    "construct",
    "construct-typing",
    "cryptography",
    "gitpython",
    "idna",
    "iniconfig",
    "jsonschema",
    "packaging",
    "pluggy",
    "pycparser",
    "pydantic",
    "pydantic_core",
    "requests",
    "typing_extensions",
    "urllib3",
]

[project.optional-dependencies]
xtest = ["pytest"]
bdd = ["behave", "pyyaml"]
linting = ["black", "pyright", "ruff"]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "pytest>=8.4.1",
    "ruff>=0.12.9",
]
