apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "entitlements.name" . }}-cm
data:
  POSTGRES_HOST: {{ .Values.postgres.host }}
  POSTGRES_USER: {{ .Values.postgres.user }}
  {{/*  POSTGRES_PASSWORD: deployment.envFrom.secretRef.attributes-secrets*/}}
  POSTGRES_DATABASE: {{ .Values.postgres.database }}
  POSTGRES_SCHEMA: {{ .Values.postgres.schema }}
