#!/usr/bin/env bash
# Installs pre-requisites for local containers
#
# Usage: tools/pre-req [apps]
#
# Examples:
#   Install conventional list of pre-reqs for your platform, if needed
#     tools/pre-reqs
#   Install specific of pre-reqs for your platform
#     tools/pre-reqs kind helm kuttl kubectl
#

TOOLS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
export PATH="$PATH:$TOOLS_DIR"

monolog TRACE "pre-reqs: [$0 $*]"

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  # shellcheck disable=SC1091
  . "$TOOLS_DIR/pre-reqs-linux.sh" "${@}"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  # shellcheck disable=SC1091
  . "$TOOLS_DIR/pre-reqs-macos.sh" "${@}"
else
  monolog ERROR "Unknown OS [${OSTYPE}]"
  exit 1
fi
