#!/usr/bin/env bash
# Wait at least 15 minutes
# Example:
#   wait-after your command

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
PROJECT_ROOT="$(cd "${APP_DIR}/../../" >/dev/null && pwd)"
export PATH="$PATH:$APP_DIR:$PROJECT_ROOT/tools"

monolog TRACE "wait-after ${*}"

wait-for-time() {
  monolog TRACE "wait-for-time $*"
  sleep 900 &
  local wpid=$!
  ("$@")
  local rval=$?
  if [[ $rval != 0 ]]; then
    monolog WARN "subcommand FAILED, rval=$rval"
  fi
  monolog TRACE "wait-for-time [subcommand done, waiting...]"
  wait $wpid
}

wait-for-time "$@"
