# Tiltfile for development of OpenTDF backend
# reference https://docs.tilt.dev/api.html
# extensions https://github.com/tilt-dev/tilt-extensions

load("ext://helm_resource", "helm_resource", "helm_repo")

#load(
#   "../opentdf.Tiltfile",
#    "opentdf_cluster_with_ingress",
#)

BACKEND_CHART_TAG = os.environ.get("BACKEND_LATEST_VERSION", "1.6.0")
EXTERNAL_URL = "http://localhost:65432"
os.putenv('QUICKSTART_BOOTSTRAP_DISABLED', 'True')

include('../quickstart/Tiltfile')

# TODO remove abacus here since we don't use it for this test
# opentdf_cluster_with_ingress(start_frontend=False)

k8s_yaml(
    helm(
        "./sdk/js/outbound-test-app/helm/secrets",
    ),
)

# execute Examples bootstrap
helm_resource(
    "keycloak-bootstrap",
    "oci://ghcr.io/opentdf/charts/keycloak-bootstrap",
    flags=[
        "--debug",
        "--version",
        BACKEND_CHART_TAG,
        "-f",
        "./sdk/js/outbound-test-app/helm/values-bootstrap.yaml",
        "--set",
        "externalUrl=%s" % EXTERNAL_URL,
    ],
    release_name="backend",
    labels="utility",
    resource_deps=["backend"],
)

k8s_yaml("./sdk/js/outbound-test-app/kubernetes.yaml")
k8s_resource(
    "opentdf-todo-react",
    resource_deps = ["keycloak-bootstrap"],
    labels="todo-react",
)

docker_build(
    "opentdf/todo-react",
    "./sdk/js/outbound-test-app/"
)

local_resource("test", "npm run test", resource_deps=["backend"])
# local_resource("outbound-test", "python3 sdk/py/test_unbound_policy.py", resource_deps=["backend"])
# local_resource("outbound-jwt-test", "cd sdk/js/outbound-test-app && npm ci && npx playwright install && npm run test", resource_deps=["outbound-app", "opentdf-outbound-demo-react-app", "backend"])