#!/usr/bin/env bash

TOOLS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
export PATH="$PATH:$TOOLS_DIR"
setopt NULL_GLOB

checkCertsExperation()
{
  certDate=$(openssl x509 -enddate -noout -in "$1"|cut -d= -f 2)
  certTimeStamp=$(date -jf "%b  %d %k:%M:%S %Y %Z" "$certDate" +%s)
  nowTimeStamp=$(date  +%s)

  [ "$certTimeStamp" -lt "$nowTimeStamp" ]
}

certificates=( "ca" "client" "reverse-proxy" )

for cert in "${certificates[@]}"
do
	if [ -f certs/"$cert".crt ]; then
    if checkCertsExperation "certs/$cert.crt"; then
      for key in certs/"$cert".*; do
        rm -f "./$key"
      done
    fi
  fi
done

#Kas and Eas check
for publicKey in certs/*-public.pem; do
  if checkCertsExperation "$publicKey"; then
    privateKey="${publicKey/public/private}"
    rm -f "./$privateKey" "./$publicKey"
  fi
done
