#!/usr/bin/env bash

NANOTDF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
PROJECT_ROOT="$(cd "$NANOTDF_DIR"/../ >/dev/null && pwd)"
export PATH="$PATH:$PROJECT_ROOT/scripts"

monolog TRACE "Running [$0${1+ }$*]"

e() {
  local rval=$?
  monolog ERROR "${@}"
  exit $rval
}

cd "$NANOTDF_DIR"
mkdir -p build/gencode ||
  e "Failed to create output folder folder 'build/gencode'"
docker build --tag ksc:0.8 --target compiler . 1> >(monolog DEBUG) 2> >(monolog TRACE) ||
  e "Failed to build kaitai struct compiler container"
docker run -it --volume "$PWD":/workdir ksc:0.8 \
  --target python \
  --outdir build/gencode \
  nanotdf.ksy 1> >(monolog DEBUG) 2> >(monolog ERROR) ||
  e "Failed to compile nanotdf.ksy"
python -m py_compile build/gencode/nanotdf.py 1> >(monolog DEBUG) 2> >(monolog ERROR) ||
  e "nanotdf.py is invalid or missing"

monolog TRACE "Finished [$0${1+ }$*]"
