name: configure-sdks
description: Check out and build one or more SDK and its CLI tool for use by xtest
inputs:
  path:
    description: The path to checkout the the SDK source code to; concatenated with branch or tag name.
  sdk:
    description: The SDK to configure; one of go, java, js
  version-info:
    description: JSON-encoded output of resolve-version.py
    required: true
outputs:
  version-a:
    description: "Object containing tag, sha, and name of a version checked out"
    value: ${{ steps.resolve.outputs.version-a }}
  version-b:
    description: "Object containing tag, sha, and name of a version checked out, if two or more were specified"
    value: ${{ steps.resolve.outputs.version-b }}
  version-c:
    description: "Object containing tag, sha, and name of a version checked out, if three or more were specified"
    value: ${{ steps.resolve.outputs.version-c }}
  version-d:
    description: "Object containing tag, sha, and name of a version checked out, if four were specified"
    value: ${{ steps.resolve.outputs.version-d }}
  heads:
    description: "JSON list of tags that represent main or branch heads"
    value: ${{ steps.resolve.outputs.heads }}

runs:
  using: composite
  steps:
    - name: identify repo url
      shell: bash
      run: |
        case "${{ inputs.sdk }}" in
          "go")
            echo "sdk_repo=opentdf/otdfctl" >> $GITHUB_ENV
            ;;
          "java")
            echo "sdk_repo=opentdf/java-sdk" >> $GITHUB_ENV
            ;;
          "js")
            echo "sdk_repo=opentdf/web-sdk" >> $GITHUB_ENV
            ;;
          *)
            echo "Invalid SDK specified: ${{ inputs.sdk }}" >> $GITHUB_STEP_SUMMARY
            exit 1
            ;;
        esac

    - name: resolve versions
      id: resolve
      shell: bash
      run: |
        if [[ $(echo "$version_info" | jq 'length') -gt 4 ]]; then
          echo "Error: Too many versions resolved in version_info: $(echo "$version_info" | jq 'length')" >> $GITHUB_STEP_SUMMARY
          exit 1
        fi

        if echo "$version_info" | jq -e '.[] | select(.err != null)' > /dev/null; then
          echo "Error: One or more errors occurred while resolving versions for ${{ inputs.sdk }}: $version_info"
          exit 1
        fi
        echo "Version Info for ${{ inputs.sdk }}: $version_info"

        version_a=$(echo "$version_info" | jq -rc '.[0] // empty')
        version_b=$(echo "$version_info" | jq -rc '.[1] // empty')
        version_c=$(echo "$version_info" | jq -rc '.[2] // empty')
        version_d=$(echo "$version_info" | jq -rc '.[3] // empty')
        echo "version-a=$version_a" >> $GITHUB_OUTPUT
        echo "version-b=$version_b" >> $GITHUB_OUTPUT
        echo "version-c=$version_c" >> $GITHUB_OUTPUT
        echo "version-d=$version_d" >> $GITHUB_OUTPUT
        head_tags=$(echo "$version_info" | jq -c '[.[] | select(.head == true) | .tag]')
        echo "head_tags=$head_tags"
        echo "heads=$head_tags" >> $GITHUB_OUTPUT
      env:
        version_info: ${{ inputs.version-info }}

    - name: checkout version a
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      if: steps.resolve.outputs.version-a != ''
      with:
        path: ${{ inputs.path }}/${{ inputs.sdk }}/src/${{ fromJson(steps.resolve.outputs.version-a).tag }}
        persist-credentials: false
        ref: ${{ fromJson(steps.resolve.outputs.version-a).sha }}
        repository: ${{ env.sdk_repo }}

    - name: checkout version b
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      if: steps.resolve.outputs.version-b != ''
      with:
        path: ${{ inputs.path }}/${{ inputs.sdk }}/src/${{ fromJson(steps.resolve.outputs.version-b).tag }}
        persist-credentials: false
        ref: ${{ fromJson(steps.resolve.outputs.version-b).sha }}
        repository: ${{ env.sdk_repo }}

    - name: checkout version c
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      if: steps.resolve.outputs.version-c != ''
      with:
        path: ${{ inputs.path }}/${{ inputs.sdk }}/src/${{ fromJson(steps.resolve.outputs.version-c).tag }}
        persist-credentials: false
        ref: ${{ fromJson(steps.resolve.outputs.version-c).sha }}
        repository: ${{ env.sdk_repo }}

    - name: checkout version d
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      if: steps.resolve.outputs.version-d != ''
      with:
        path: ${{ inputs.path }}/${{ inputs.sdk }}/src/${{ fromJson(steps.resolve.outputs.version-d).tag }}
        persist-credentials: false
        ref: ${{ fromJson(steps.resolve.outputs.version-d).sha }}
        repository: ${{ env.sdk_repo }}

    - name: post checkout cleanups
      if: inputs.sdk == 'java'
      run: |
        ${{ inputs.path }}/scripts/post-checkout-java.sh
      shell: bash

    - name: save env from version-info
      shell: bash
      run: |
        # Iterate over each version and save the env variable to a file
        for version in $(echo "${version_info}" | jq -c '.[]'); do
          tag=$(echo "$version" | jq -r '.tag')
          env=$(echo "$version" | jq -r '.env // empty')
          if [[ -n "$env" ]]; then
            echo "$env" > "${{ inputs.path }}/${{ inputs.sdk }}/src/${tag}.env"
          fi
        done
      env:
        version_info: ${{ inputs.version-info }}

