apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abacus
  labels:
    helm.sh/chart: abacus-0.1.0
    app.kubernetes.io/name: abacus
    app.kubernetes.io/instance: chart
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: "localhost"
      http:
        paths:
          - path: "/(.*)"
            pathType: "Prefix"
            backend:
              service:
                name: "abacus"
                port:
                  number: 80
    - host: "opentdf.local"
      http:
        paths:
          - path: "/(.*)"
            pathType: "Prefix"
            backend:
              service:
                name: "abacus"
                port:
                  number: 80
