#!/bin/bash

START_APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
PROJECT_ROOT="$(cd "${START_APP_DIR}/../../" >/dev/null && pwd)"
export PATH="$PATH:$PROJECT_ROOT/tools"

if [ -z "$KAS_CERTIFICATE" ]; then
  CERTS_DIR="$PROJECT_ROOT/certs"
  monolog INFO "KAS.entrypoint: Waiting for certificate files to appear in [$CERTS_DIR]"
  wait-for-file "$CERTS_DIR/.env"
  monolog INFO "KAS.entrypoint: Certificate file found. Continuing."

  KEYCLOAK_PUBLIC_KEY="${KEYCLOAK_PUBLIC_KEY:${CERTS_DIR}/keycloak-public.pem}"
  CA_CERT_PATH="${CA_CERT_PATH:-/certs/ca.crt}"

  . "$PROJECT_ROOT/certs/.env"
else
  monolog INFO "KAS.entrypoint: Not loading test cert environment"
fi

export CA_CERT_PATH
export EAS_CERTIFICATE
export KAS_EC_SECP256R1_PRIVATE_KEY
export KAS_EC_SECP256R1_CERTIFICATE
export KAS_PRIVATE_KEY
export KAS_CERTIFICATE
export KEYCLOAK_PUBLIC_KEY

if [ -z $1]; then
  PORT=8000
else
  PORT=$1
fi

monolog INFO "Starting KAS on port $PORT"
(
  cd $PROJECT_ROOT/kas_app
  gunicorn --config gunicorn.conf.py -b :$PORT wsgi:app
)
