# Header
NANOTDF_HEADER_MAGIC_NUM_AND_VERSION = b"\x4c\x31\x4c"
NANOTDF_HEADER_KAS_LOCATOR = b"\xff\x01\x00"
NANOTDF_HEADER_ECC_MODE = b"\x80"

# No signature
NANOTDF_HEADER_SYMMETRIC_AND_SIG_PAYLOAD_MODE = b"\x00"
NANOTDF_HEADER_POLICY_MODE = b"\x01"
NANOTDF_HEADER_POLICY_PLAINTEXT = b"\x00\x02\xff\xff"
NANOTDF_HEADER_POLICY_AND_PAYLOAD_BINDING = b"\x00" * 64
NANOTDF_HEADER_KEY = b"\x00" * 33

# Payload
NANOTDF_PAYLOAD_LENGTH = b"\x00\x00\x10"
NANOTDF_PAYLOAD_IV = b"\x00\x00\x01"
NANOTDF_PAYLOAD_BODY = b"\x00" * 5
NANOTDF_PAYLOAD_TAG = b"\x00" * 8

NANOTDF = NANOTDF_HEADER_MAGIC_NUM_AND_VERSION
NANOTDF += NANOTDF_HEADER_KAS_LOCATOR
NANOTDF += NANOTDF_HEADER_ECC_MODE
NANOTDF += NANOTDF_HEADER_SYMMETRIC_AND_SIG_PAYLOAD_MODE
NANOTDF += NANOTDF_HEADER_POLICY_MODE
NANOTDF += NANOTDF_HEADER_POLICY_PLAINTEXT
NANOTDF += NANOTDF_HEADER_POLICY_AND_PAYLOAD_BINDING
NANOTDF += NANOTDF_HEADER_KEY
NANOTDF += NANOTDF_PAYLOAD_LENGTH
NANOTDF += NANOTDF_PAYLOAD_IV
NANOTDF += NANOTDF_PAYLOAD_BODY
NANOTDF += NANOTDF_PAYLOAD_TAG
