basePath: ""
fullnameOverride: abacus
oidc:
  clientId: dcr-test
  queryRealms: tdf
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class:
  className: nginx
  hosts:
    - host: localhost
      paths: &paths
        - path: /(.*)
          pathType: Prefix
    - host: opentdf.local
      paths: *paths
