include('../projects/backend/Tiltfile')

k8s_resource(
    "opentdf-xtest",
    resource_deps=["backend"],
    auto_init=False,
    trigger_mode=TRIGGER_MODE_MANUAL
)

local_resource(
    "test-client-web",
    "npm run test",
    resource_deps=["backend"]
)

local_resource(
    "frontend-test",
    "CI=true npm run test:playwright",
    dir="../projects/frontend",
    resource_deps=["backend"]
)
