include('../projects/backend/Tiltfile')
include('../projects/backend/xtest.Tiltfile')

local_resource(
    "test-client-web",
    "npm run test",
    resource_deps=["xtest-keycloak-bootstrap"]
)

local_resource(
    "frontend-test",
    "CI=true npm run test:playwright",
    dir="../projects/frontend",
    resource_deps=["xtest-keycloak-bootstrap"]
)
