apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kas.name" . }}-cm
  labels:
    app.kubernetes.io/name: {{ include "kas.name" . }}-cm
    helm.sh/chart: {{ include "kas.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: kas
data:
  EAS_HOST: {{ .Values.endpoints.easHost }}
  FLASK_DEBUG: "True"
  GUNICORN_WORKERS: "1"
  # OIDC_PUBKEY_ENDPOINT: {{ .Values.endpoints.oidcPubkeyEndpoint }}
  KEYCLOAK_HOST: {{ .Values.endpoints.oidcPubkeyEndpoint }}
  # TODO:  Do we want to make this the default?
  USE_KEYCLOAK: "1"
  LOGLEVEL: DEBUG
