name: Vulnerability Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm ci
    - name: Run unit tests
      run: npm run test
    # - name: Install Playwright
      # run: npx playwright install --with-deps
    # - name: Run Playwright tests
      # run: xvfb-run npm run test:playwright
    # - name: Upload test results
      # if: always()
      # uses: actions/upload-artifact@v2
      # with:
        # name: playwright-test-results
        # path: test-results
