/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: operations["read_semver__get"];
  };
  "/healthz": {
    get: operations["read_liveness_healthz_get"];
  };
  "/v1/attr": {
    get: operations["read_attribute_v1_attr_get"];
    post: operations["create_attribute_v1_attr_post"];
  };
  "/v1/attrName": {
    post: operations["read_attribute_v1_attrName_post"];
  };
  "/v1/authorityNamespace": {
    get: operations["read_authority_namespace_v1_authorityNamespace_get"];
    post: operations["create_authority_namespace_v1_authorityNamespace_post"];
  };
}

export interface components {
  schemas: {
    Attribute: {
      authorityNamespace: string;
      name: string;
      order: string[];
      rule: components["schemas"]["AttributeRuleType"];
      state?: string;
    };
    /** An enumeration. */
    AttributeRuleType: "hierarchy" | "anyOf" | "allOf";
    HTTPValidationError: {
      detail?: components["schemas"]["ValidationError"][];
    };
    /** An enumeration. */
    ProbeType: "liveness" | "readiness";
    ValidationError: {
      loc: string[];
      msg: string;
      type: string;
    };
  };
}

export interface operations {
  read_semver__get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  read_liveness_healthz_get: {
    parameters: {
      query: {
        probe?: components["schemas"]["ProbeType"];
      };
    };
    responses: {
      /** Successful Response */
      204: never;
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_attribute_v1_attr_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Attribute"][];
        };
      };
    };
  };
  create_attribute_v1_attr_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Attribute"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Attribute"];
      };
    };
  };
  read_attribute_v1_attrName_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Attribute"][];
        };
      };
    };
  };
  read_authority_namespace_v1_authorityNamespace_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  create_authority_namespace_v1_authorityNamespace_post: {
    parameters: {
      query: {
        request_authority_namespace: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}

export interface external { }
