# Tiltfile for development of OpenTDF backend
# reference https://docs.tilt.dev/api.html
# extensions https://github.com/tilt-dev/tilt-extensions

load(
    "../opentdf.Tiltfile",
    "opentdf_cluster_with_ingress",
)

opentdf_cluster_with_ingress()

local_resource("test abacus", "curl http://localhost:8080", auto_init=False, resource_deps=["backend", "frontend"])
# local_resource("test", "npm run test", resource_deps=["backend", "frontend"])
