name: Abacus-Playwright-Test
on:
  push:
    branches:
      - 'feature/PLAT-1967'
#  schedule:
#    - cron: "0 8 * * *"
jobs:
  abacus-integration-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: git submodule update --remote --recursive
        if: github.event.schedule

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          setup-tools: |
            kubectl
            helm
            tilt
          # This should be in sync with the minikube-deployed kube version below
          kubectl: "1.23.1"
          helm: "3.8.0"
          tilt: "0.26.2"
      - run: |
          kubectl version --client
          kustomize version
          tilt version
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@master
        with:
          minikube-version: 1.25.1
          # This should be in sync with the setup-tools version above
          kubernetes-version: 1.23.1
      - name: Run tilt
        run: |-
          cd projects/backend
          kubectl version
          cd client-web-test
          tilt ci

      - name: Run Frontend
        run: |-
          cd projects/frontend
          npm ci
          npx playwright install --with-deps
      - name: Run Playwright tests
        run: xvfb-run npm run test:playwright
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-test-results
          path: test-results
