name: Abacus-and-API-Playwright-Tests
on:
  push:
    branches: [plat_2985_integrate_test_results_into_testrail]
#  pull_request:
#    branches: [main]
#  repository_dispatch:
#    types: [xtest]
#  schedule:
#    - cron: "0 7 * * 2,4,6"
#  workflow_dispatch:
#    inputs:
#      backendVersion:
#        required: true
#        type: string
#      frontendVersion:
#        required: true
#        type: string
jobs:
  abacus-playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: abacus-and-api-integration-tests
    permissions:
      contents: read
      packages: read
    strategy:
      matrix:
        kasversion: [ python-kas, go-kas ]
    steps:
      - uses: actions/checkout@v3
      - name: Set kas-related environment variable
        shell: bash
        run: echo "KAS_VERSION=${{ matrix.kasversion }}" >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: https://npm.pkg.github.com
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |-
          npm ci
          npx playwright install
          pip install trcli
      - uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: |
            kubectl
            helm
            tilt
          kubectl: "1.24.1"
          helm: "3.9.2"
          tilt: "0.31.2"
      - run: |
          kubectl version --client
          kustomize version
          tilt version
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@master
        with:
          minikube-version: 1.26.0
          # This should be in sync with the setup-tools version above
          kubernetes-version: 1.24.1
      - name: Run tilt
        run: |-
          [[ -z "${{github.event.inputs.backendVersion}}" ]] && export BACKEND_LATEST_VERSION=$(skopeo list-tags docker://ghcr.io/opentdf/charts/backend \
          | python3 -c "import sys, json; sys.stdout.write([tag for tag in json.load(sys.stdin)['Tags'] if not tag.endswith('.sig')][-1])") || export BACKEND_LATEST_VERSION="${{github.event.inputs.backendVersion}}"
          echo "Testing Backend [$BACKEND_LATEST_VERSION]">>$GITHUB_STEP_SUMMARY
          
          [[ -z "${{github.event.inputs.frontendVersion}}" ]] && export FRONTEND_LATEST_VERSION=$(skopeo list-tags docker://ghcr.io/opentdf/charts/abacus \
          | python3 -c "import sys, json; sys.stdout.write([tag for tag in json.load(sys.stdin)['Tags'] if not tag.endswith('.sig')][-1])") || export FRONTEND_LATEST_VERSION="${{github.event.inputs.frontendVersion}}"
          echo "Testing Frontend [$FRONTEND_LATEST_VERSION]">>$GITHUB_STEP_SUMMARY
          kubectl version
          tilt ci
      - name: 'Authenticate to Google Cloud'
        id: 'gcp-auth'
        uses: 'google-github-actions/auth@35b0e87d162680511bf346c299f71c9c5c379033'
        with:
          workload_identity_provider: 'projects/1053957112592/locations/global/workloadIdentityPools/github-actions-oidc-pool/providers/github-actions-oidc-provider'
          service_account: 'qa-sa-for-gha@prj-infra-automation-ktbz.iam.gserviceaccount.com'

      - name: 'Output team GCP secrets'
        id: 'gcp-secrets'
        uses: google-github-actions/get-secretmanager-secrets@4d6d3dfd94110800dda8d84109cb6da0f6a5919d
        with:
          secrets: |-
            TESTRAIL_PASS:prj-infra-automation-ktbz/qa_TESTRAIL_PASS
      - name: Integrate results into TestRail
        env:
          TESTRAIL_PASS: ${{ steps.gcp-secrets.outputs.TESTRAIL_PASS }}
        run: |
          trcli -y \
          --host https://virtru.testrail.com \
          --project "Abacus Website" \
          --username testerfour@trusteddataformat.org \
          --password $process.env.TESTRAIL_PASS \
          parse_junit \
          --title "Playwright Automated Test Run" \
          --file "/home/runner/work/tests/tests/abacus-and-api-integration-tests/test-results/junit-report.xml"
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-test-results
          path: ./abacus-and-api-integration-tests/test-results

