on:
  workflow_dispatch:

jobs:
  sync:
    name: "🔀 git submodules update --remote"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: |
          git submodule update --remote --recursive
      - if: steps.auto-commit.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
